### ISSUE TITLE
Ignore Emojis

### ISSUE THREAD

**Issue by BoxedBrain** [blueswen/mkdocs-glightbox#1]
Hi,

first, thanks for your plugin! 👍

When using mkdocs-material with the [emoji feature](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/), for example by typing:
```
Hi :man_raising_hand:
```
It is also picked up by the lightbox and shown inside the loop, which is quite destroying the user experience.
Is there a way to exclude them?

**Comment by blueswen** [comment]
@BoxedBrain Thanks for reporting! Didn't notice the emoji issue before.

I add a class filter (including three index from [PyMdown Extensions](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/#supported-emoji-providers)) to skip the glightbox wrapping in version 0.1.7. If the new version solves your problem, you can close this issue.

**Comment by BoxedBrain** [comment]
@blueswen Thanks for your fast fix, it solved the issue! ❤️
