### ISSUE TITLE
[Feature request] Group images (gallery)

### ISSUE THREAD

**Issue by botkero** [blueswen/mkdocs-glightbox#11]
Hello,

As far as I can see, you can switch between all images on a site, when glightbox is activated. 
When you look into https://biati-digital.github.io/glightbox/, then you will see that each gallery have a predefined number of images.

- Simple Image Gallery has 6 images
- Images with Description has 3 images

I do not know how hard it is to implement such a detail, but I think it would be a great extension. 
Anyway thank you for this plug-in great work!

**Comment by blueswen** [comment]
The gallery feature was released in version 0.3.1. You can check more details on [gallery](https://blueswen.github.io/mkdocs-glightbox/gallery/gallery/).
