### ISSUE TITLE
Error reading page

### ISSUE THREAD

**Issue by vvssttkk** [blueswen/mkdocs-glightbox#20]
when build mkdocs get `ERROR    -  Error reading page 'index.md': 'NoneType' object has no attribute 'group'` (v0.4.3)
but in v0.3.2 all good

**Comment by blueswen** [comment]
Do you mean v0.3.4? The NoneType bug should be fixed in v0.3.4. Could you provide your code or a reproducible sample code?

**Comment by blueswen** [comment]
Sorry, I forgot to publish a new release on the GitHub repository last week 😅. You can download the latest v0.3.4 from PyPI.
