### ISSUE TITLE
`glightbox-mkdocs` plugin does not work with `mkdocs-multirepo-plugin`

### ISSUE THREAD

**Issue by mlcooper** [blueswen/mkdocs-glightbox#23]
On its own, I can get the [glightbox-mkdocs](https://github.com/blueswen/mkdocs-glightbox) plugin to work without any issues. My images become 'zoomable' which is the desired effect I am looking for.

However, when I import that same repo with the [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin), the 'zoomable' feature of my images in markdown no longer are 'zoomable'. 

I installed the `glightbox-mkdocs` plugin in both my 'parent' multi-repo repo and the child repo, but that did not help. 

You can see below that the `glightbox` script is **missing** when hosted on Gitlab pages with the `mkdocs-multirepo-plugin`, but the script is **present** when hosted on my local workstation via `mkdocs serve`:

# Hosted on Gitlab Pages Using [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin)
![image](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/9505606/f34c7f14-167c-4408-bb95-4c67b009421e)

# Locally Hosted by running `mkdocs serve`
![image](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/9505606/5cb98280-8bcf-4c66-953f-a23dfcfd6d32)

**Comment by blueswen** [comment]
Hi @mlcooper

Do you mean in locally hosted using glightbox-mkdocs and  [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin) at the same time is working fine but when published with GitLab page is failed? Could you provide a reproducible repo and your mkdocs.yaml for the GitLab page?

**Comment by mlcooper** [comment]
I had who `plugins:` sections, one in mkdocs.yml and one in an `inherited` mkdocs.yml file and they did NOT merge (perhaps by design?). Anyway, when I moved `plugins:` to mkdocs.yml only, this now worked.
