### ISSUE TITLE
Enable glightbox don't have search

### ISSUE THREAD

**Issue by hautph** [blueswen/mkdocs-glightbox#24]
Hi,

When I active glightbox, don't have a search, please help me how to fix

Thanks.

**Comment by blueswen** [comment]
Hi @hautph ,

The search plugin is the default plugin, so you have to add it back when using other plugins. See more discussion on https://github.com/blueswen/mkdocs-glightbox/issues/18.

```yaml
plugins:
  - search
  - glightbox
```

**Comment by hautph** [comment]
It's running now, thanks.
