### ISSUE TITLE
Ignore neoteroi-mkdocs elements

### ISSUE THREAD

**Issue by carried-away** [blueswen/mkdocs-glightbox#28]
Hello,

I'm using [neoteroi cards](https://www.neoteroi.dev/mkdocs-plugins/cards/) and the glightbox plugin conflicts with the imgs.

Maybe it's currently possible to ignore these imgs but I am not having much success. I think it's because the neoteroi plugin does not allow imgs to have classes bound to them via the [input object mechanism](https://www.neoteroi.dev/mkdocs-plugins/cards/#input-object)

I tried enabling 

```yaml
- glightbox:
      skip_classes: 
        - skip
```

and applying the skip class to the actual card element to be ignored by glightbox, but glightbox only adheres to img, as it should. 

I guess what I'm asking is, is it currently possible to ignore classes of things other than imgs? Right now, I can only get things to work by disabling glightbox on the page completely, which i really don't want to do as it's an awesome plugin.

**Comment by blueswen** [comment]
Hi @carried-away,

I added a new feature in [v0.3.6](https://github.com/blueswen/mkdocs-glightbox/releases/tag/v0.3.6) to enable lightbox of images separately by adding `on-glb` class and keeping others not affected, which may fit your requirements. You can check the demo and details on [documents](https://blueswen.github.io/mkdocs-glightbox/disable/manual/).

**Comment by carried-away** [comment]
Perfect!!! Thank you, Happy New Year!
