### ISSUE TITLE
Is there a way to set glightbox-manual: true globally?

### ISSUE THREAD

**Issue by aborruso** [blueswen/mkdocs-glightbox#39]
Hi,
thank you very much for this plugin.

Is there a way to set `glightbox-manual: true` globally, without the need to include it on every page in the meta?

I would like it always off, and activate it by inserting `{ .on-glb }` where needed.

Thank you

**Comment by blueswen** [comment]
@michalfapso helped implement this feature on #29 which was released on [v0.4.0](https://github.com/blueswen/mkdocs-glightbox/releases/tag/v0.4.0). You can get more details on our [documentation](https://blueswen.github.io/mkdocs-glightbox/flexibility/enable-by-image-or-page/).

**Comment by aborruso** [comment]
thank you very much @blueswen and @michalfapso
