### ISSUE TITLE
Consider supporting custom `skip_class` ?

### ISSUE THREAD

**Issue by luolingchun** [blueswen/mkdocs-glightbox#5]
I want to skip custom `img` tag. 

https://github.com/blueswen/mkdocs-glightbox/blob/main/mkdocs_glightbox/plugin.py#L71-L73

**Comment by blueswen** [comment]
@luolingchun Thanks for advices. The new plugin option ```skip_classes``` in v0.3.0 may meet your requirements, you can check the demo on https://blueswen.github.io/mkdocs-glightbox/disable/image/.
