### ISSUE TITLE
Ignore Shields

### ISSUE THREAD

**Issue by TRaSH-** [blueswen/mkdocs-glightbox#6]
After installing glightbox, i noticed when you click on a shield it also opens the image, what breaks the actual action of the shields.

![image](https://user-images.githubusercontent.com/6155095/196261637-d84b3638-731d-418b-a005-e4c6e2d1fa71.png)

Any way to disable/ignore shields ?

**Comment by blueswen** [comment]
Adding an `off-glb` class to the image attribute or adding an existing image class as `skip_classes ` to plugin options could disable glightbox effect by the image. Check more details on [Disable by image](https://blueswen.github.io/mkdocs-glightbox/disable/image/).

**Comment by TRaSH-** [comment]
I tried that, but it breaks the shield, or I'm doing something wrong.
`[![Discord chat](https://img.shields.io/discord/492590071455940612?style=for-the-badge&color=4051B5&logo=discord)](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}`

**Comment by blueswen** [comment]
Try to add off-glb class to the image as follows:

`[![Discord chat](https://img.shields.io/discord/492590071455940612?style=for-the-badge&color=4051B5&logo=discord){.off-glb}](https://trash-guides.info/discord){:target="_blank" rel="noopener noreferrer"}`

It's working on my machine with your doc [Guides](https://github.com/TRaSH-/Guides).

**Comment by TRaSH-** [comment]
Hmm
Back to the drawing board when I get home and retest it.

**Comment by TRaSH-** [comment]
Thnx it works, i was trying to add it outside the brackets and that didn't work for the shields.
