### ISSUE TITLE
[Feature request] Support switch between themes (typicallly light/dark modes)

### ISSUE THREAD

**Issue by Guts** [blueswen/mkdocs-glightbox#7]
Hello,

Nice plugin here, thanks!

Would you consider adding support for color theme and dynamic change?

I see you use the Material for Mkdocs theme for your demao and it's one of its main feature. It would be nice to reuse the colors schemes for the description/title banner :)

**Comment by blueswen** [comment]
The synchronized lightbox caption dark mode with Material for MkDocs feature was released in version 0.3.1. You can check the effect on [capiton](https://blueswen.github.io/mkdocs-glightbox/caption/caption/).

**Comment by Guts** [comment]
Thanks you!

:clap:
